### ISSUE TITLE
Problem with DTC

### ISSUE THREAD

**Issue by Luc-Saccoccio** [Luc-Saccoccio/dtcli#1]
While querying a random DTC, this happened:

```
┌─<luc@Anarchiste in ~>
└─<>──» dtcli
Retrieiving failed : url https://danstonchat.com/8.html
Traceback (most recent call last):
  File "/home/luc/.local/bin/dtcli", line 8, in <module>
    sys.exit(main())
  File "/home/luc/.local/pipx/venvs/dtcli/lib/python3.8/site-packages/dtcli/command.py", line 73, in main
    banner(title, {'dtc': 'DTC', 'nsf': 'NSF', 'bash': 'QDB'}[args.website], number, tmp_url, args.hide_title)
UnboundLocalError: local variable 'title' referenced before assignment
```

**Comment by Luc-Saccoccio** [comment]
Same thing for 
```
┌─<luc@Anarchiste in ~/work/Informatique/dtcli>
└─<git@dtcli:master>──» dtcli -v
Required conditions:  {'force': False, 'lines': False, 'over': False, 'under': False}
testing DTC n°4470, url https://danstonchat.com/4470.html
Retrieiving failed : url https://danstonchat.com/4470.html
Traceback (most recent call last):
  File "/home/luc/.local/bin/dtcli", line 8, in <module>
    sys.exit(main())
  File "/home/luc/.local/pipx/venvs/dtcli/lib/python3.8/site-packages/dtcli/command.py", line 73, in main
    banner(title, {'dtc': 'DTC', 'nsf': 'NSF', 'bash': 'QDB'}[args.website], number, tmp_url, args.hide_title)
UnboundLocalError: local variable 'title' referenced before assignment
```

**Comment by Luc-Saccoccio** [comment]
Same for 806 
```
┌─<luc@Anarchiste in ~>
└─<>──» dtcli -v
Required conditions:  {'force': False, 'lines': False, 'over': False, 'under': False}
testing DTC n°806, url https://danstonchat.com/806.html
Retrieiving failed : url https://danstonchat.com/806.html
Traceback (most recent call last):
  File "/home/luc/.local/bin/dtcli", line 8, in <module>
    sys.exit(main())
  File "/home/luc/.local/pipx/venvs/dtcli/lib/python3.8/site-packages/dtcli/command.py", line 73, in main
    banner(title, {'dtc': 'DTC', 'nsf': 'NSF', 'bash': 'QDB'}[args.website], number, tmp_url, args.hide_title)
UnboundLocalError: local variable 'title' referenced before assignment
```

**Comment by Luc-Saccoccio** [comment]
Reason : I'm bad at passing arguments to functions I wrote myself :roll_eyes:
